"""Policy-neutral component contracts for the synthetic environment."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Hashable, Mapping, Protocol, Sequence, runtime_checkable

from .state import WorldState


Task = Hashable
OperationalAction = Hashable


@dataclass(frozen=True)
class Opportunity:
    """A development resource generated by operation, not development itself."""

    available: bool
    payload: object | None = None


@dataclass(frozen=True)
class DevelopmentDecision:
    """A null action or development of a recipient on a competence dimension."""

    recipient: Hashable | None = None
    competence: Hashable | None = None

    def __post_init__(self) -> None:
        if (self.recipient is None) != (self.competence is None):
            raise ValueError("recipient and competence must both be set or both be null")

    @property
    def is_null(self) -> bool:
        return self.recipient is None


NULL_DEVELOPMENT = DevelopmentDecision()


@dataclass(frozen=True)
class InformationContract:
    """Information/coordination authorized for one policy-facing module."""

    name: str
    reveal_state: bool = True
    reveal_immediate_rewards: bool = True
    reveal_continuation_values: bool = False
    coordinate_operational_and_development_value: bool = False


@dataclass(frozen=True)
class PolicyView:
    """Immutable policy-facing view produced by an information component."""

    state: WorldState | None
    task: Task
    immediate_rewards: tuple[tuple[OperationalAction, float], ...]
    continuation_values: tuple[tuple[OperationalAction, float], ...]
    contract: InformationContract

    def rewards(self) -> Mapping[OperationalAction, float]:
        return dict(self.immediate_rewards)

    def continuations(self) -> Mapping[OperationalAction, float]:
        return dict(self.continuation_values)


@runtime_checkable
class RandomSource(Protocol):
    def random(self) -> float: ...


@runtime_checkable
class TaskProcess(Protocol):
    def task_at(
        self,
        time: int,
        state: WorldState,
        history: Sequence[object],
    ) -> Task: ...


@runtime_checkable
class CompetenceModel(Protocol):
    def initial_state(self) -> WorldState: ...

    def validate(self, state: WorldState) -> None: ...


@runtime_checkable
class OpportunityKernel(Protocol):
    def probability(
        self,
        state: WorldState,
        task: Task,
        operational_action: OperationalAction,
        history: Sequence[object],
    ) -> float: ...


@runtime_checkable
class DevelopmentKernel(Protocol):
    def admissible_actions(
        self,
        state: WorldState,
        opportunity: Opportunity,
    ) -> tuple[DevelopmentDecision, ...]: ...

    def transition(
        self,
        state: WorldState,
        opportunity: Opportunity,
        action: DevelopmentDecision,
    ) -> WorldState: ...


@runtime_checkable
class RewardModel(Protocol):
    def operational_reward(
        self,
        state: WorldState,
        task: Task,
        operational_action: OperationalAction,
    ) -> float: ...


@runtime_checkable
class ResourceModel(Protocol):
    @property
    def beta(self) -> float: ...

    def development_cost(self, action: DevelopmentDecision) -> float: ...

    def development_is_admissible(
        self,
        state: WorldState,
        action: DevelopmentDecision,
        opportunity: Opportunity,
    ) -> bool: ...


@runtime_checkable
class InformationModel(Protocol):
    def view(
        self,
        contract: InformationContract,
        state: WorldState,
        task: Task,
        immediate_rewards: Mapping[OperationalAction, float],
        continuation_values: Mapping[OperationalAction, float],
    ) -> PolicyView: ...


@runtime_checkable
class Policy(Protocol):
    """Policy-facing interface; policies are external to the world."""

    def choose_operational_action(self, view: PolicyView) -> OperationalAction: ...

    def choose_development_action(
        self,
        view: PolicyView,
        opportunity: Opportunity,
        admissible_actions: tuple[DevelopmentDecision, ...],
    ) -> DevelopmentDecision: ...
